<?php $form = $this->addForm; ?>
<style>
#gMap{
 height: 350px;
 width: 940px;
}
</style>
<div class="title">
	<h3><?php echo $this->pageTitle;?></h3>
	<hr />
</div>
<div class="margin-top20 row">
	<div class="shipper-container">
		<?php echo $this->form()->openTag($form);?>
		<?php echo $this->formRow($form->get('broker_id')); ?>
		<div class="span5">
			<div class="control-group">
				<label class="control-label" for="name">Broker Name</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('name')); ?>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="name">Insurance Company</label>
				<div class="controls" style='width:291px'>
				<?php echo $this->formRow($form->get('insurance_id')); ?>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="address">Address</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('address')); ?>
			</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="phone">Office Phone</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('phone')); ?>
			</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="reference">reference</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('reference')); ?>
			</div>
			</div>
		</div>
		<div class="span5">
			<div class="control-group">
				<label class="control-label" for="email">email</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('email')); ?>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="mobile">Mobile</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('mobile')); ?>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="latitude">Latitude</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('latitude')); ?>
			</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="longitude">Longitude</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('longitude')); ?>
			</div>
			</div>
		</div>
		<div style="clear:both; padding-top:10px;padding-bottom:10px; margin: auto; width:960px;border-radius:6px; background-color:#E5E3DF">
			<div id="gMap" style="margin:auto"></div>
		</div>
		<div class="text-center" style="margin-top:15px">
            <?php echo $this->formSubmit($form->get('submit')); ?>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>

<div id="invalid-company-template" class="modal hide fade">
	<div class="modal-body">
		<div class="alert  alert-block">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4>Broker Not Saved!</h4>
			<h5>Please check below shown errors:</h5>
			<div id="company-errors"></div>
		</div>
	</div>
</div>
<div id="valid-company-template" class="modal hide fade">
	<div class="modal-body">
		<div class="alert  alert-success">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4>Broker saved successfuly</h4>
			<div id="company-messages">
				You will now be redirected to broker listings.
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	// Initialize Google Map
	$('#gMap').gmap3({
     	 action: 'init',
         options:{
         center:[0, 0],
         mapTypeId: google.maps.MapTypeId.Map,
         zoom: 2,
         scrollwheel: false
         },
         callback: function(){}
	});
	$(document).on("submit","#frm_manage",function(e){
		if(!e.isDefaultPrevented()){
			var companyForm = $(this);
			var message = false;
			companyForm.queue(function(next){
				message = new Message({
                    beforeShow:function (self) {
                        this.alternateMessage = this.showLoadingMessage("Please wait while saving broker...");
                    },
                    onBlock:next
                });
			}).queue(function(next){
				$.ajax({
					url : companyForm.attr("action"),
					data : companyForm.serialize(),
					type : "POST",
					dataType : "json",
					success : function(data){
						if(data.response && data.response.success && data.redirect_url){
							$("#valid-company-template").modal("show");
							setTimeout(function(){
								document.location.href = data.redirect_url;
							},1000);
						} else {
							$("#company-errors").html(data.response.message);
							$("#invalid-company-template").modal("show");
						}
					},
					error : function(){
						next();
					} 
				}).complete(next);
			}).queue(function(next){
				message.close();
				next();
			});
			e.preventDefault();
		}
	});
});

//Set current geo-loaction on Map
if($("#latitude").attr("value")=="" && $("#longitude").attr("value")=="")
{
	var url = "http://www.geoplugin.net/json.gp?jsoncallback=?";

	$(document).queue(function(next){

		if(navigator.geolocation) {
    		var locationMarker = null;
    		navigator.geolocation.getCurrentPosition(function(position) {
        		if(locationMarker) {
					return;
        		}
        		$('#gMap').gmap3('setDefault', {init:{center:[ position.coords.latitude,position.coords.longitude ]}});
           		$("#latitude").attr("value",position.coords.latitude);
       			$("#longitude").attr("value",position.coords.longitude);

       			next();
    		}, function() {
    			
    		});
    	} 
    	
    	if($("#latitude").attr("value")=="" && $("#longitude").attr("value")=="") {    		
    		$.getJSON(url, function(data){
            	if(data['geoplugin_status'] == 200){
        	        // Do something with the data
        	    	$('#gMap').gmap3('setDefault', {init:{center:[ data["geoplugin_latitude"],data["geoplugin_longitude"] ]}});
    				//$('#gMap').gmap3({action: 'setCenter', args:[ data["geoplugin_latitude"],data["geoplugin_longitude"] ]});
               		$("#latitude").attr("value",data["geoplugin_latitude"]);
           			$("#longitude").attr("value",data["geoplugin_longitude"]);
        	    }
        	    else
        	    {
        	    	$('#gMap').gmap3('setDefault', {init:{center:[ 0,0 ]}});
               		$("#latitude").attr("value",0);
           			$("#longitude").attr("value",0);
        	    }
        	}).complete(next);
    	}
	}).queue(function(next){
		// Set Marker to the current geo-location
       	$('#gMap').gmap3({ 
            action: 'addMarker',
            latLng:[$("#latitude").attr("value"),$("#longitude").attr("value")],
			options:{
            	draggable: true,
                animation: google.maps.Animation.DROP
            },
            events:{
            	drag: function(marker, event, data) {
            		var pos = marker.getPosition();
                	$("#latitude").attr("value",pos.lat());
                	$("#longitude").attr("value",pos.lng());
            	}
            }
        });
		next();
	});    	
} else {
	// Set Marker to the current geo-location
	//$("#mark-fixed").removeAttr("checked");
   	$('#gMap').gmap3({ 
        action: 'addMarker',
        latLng:[$("#latitude").attr("value"),$("#longitude").attr("value")],
		options:{
            animation: google.maps.Animation.DROP,
            draggable:true
        },
        events:{
        	drag: function(marker, event, data) {
        		var pos = marker.getPosition();
            	$("#latitude").attr("value",pos.lat());
            	$("#longitude").attr("value",pos.lng());
        	}
        }
    });
   	$('#gMap').gmap3({
	    action:"panTo",
	    args: [new google.maps.LatLng($("#latitude").attr("value"),$("#longitude").attr("value"))]
    });
	var map = $('#gMap').gmap3("get");
	map.setZoom(5);
}
// Callback to auto set marker based on address
$("#address, #city, #plz, #country").on("blur",function(){
	if($("#mark-fixed").attr("checked")!="checked") return;
	$('#gMap').gmap3({
		action:'getAddress',
		address:($("#address").attr("value")+ " " + $("#plz").attr("value")+ " " + $("#city").attr("value")+ " " + $("#country").attr("value")),
		callback:function(results){
			if (!results) return;
			var item = results[0];
			/*$("#gMap").gmap3({action:'clear', name:'marker'});*/
			$("#gMap").gmap3({action:'clear', name:'marker'},{
    				action:'addMarker',
					latLng:item.geometry.location,
					options:{
				        	draggable: true,
				        	animation: google.maps.Animation.DROP
				        },
				        events:{
				        	drag: function(marker, event, data) {
				        		var pos = marker.getPosition();
				            	$("#latitude").attr("value",pos.lat());
				            	$("#longitude").attr("value",pos.lng());
				        	}
				        }
				});
			var pos = item.geometry.location;
			$("#latitude").attr("value",pos.lat());
        	$("#longitude").attr("value",pos.lng());
        	
			$('#gMap').gmap3({
			    action:"panTo",
			    args: [new google.maps.LatLng($("#latitude").attr("value"),$("#longitude").attr("value"))]
		});
			var map = $('#gMap').gmap3("get");
			map.setZoom(5);
		}
	});
});

// Callback to auto set marker based on latitude and longitude
$("#latitude,#longitude").on("blur",function(){
	if($("#mark-fixed").attr("checked")!="checked") return;
    $("#gMap").gmap3(
		{action:'clear', name:'marker'},
		{
			action:'addMarker',
			latLng:[$("#latitude").attr("value"),$("#longitude").attr("value")],
			options:{
				draggable: true,
				animation: google.maps.Animation.DROP
			},
			events:{
				drag: function(marker, event, data) {
			    	var pos = marker.getPosition();
			        $("#latitude").attr("value",pos.lat());
			        $("#longitude").attr("value",pos.lng());
				}
			}
		}
	);
	
    $('#gMap').gmap3({
	    action:"panTo",
	    args: [new google.maps.LatLng($("#latitude").attr("value"),$("#longitude").attr("value"))]
    });
	var map = $('#gMap').gmap3("get");
	map.setZoom(5);
});
$(".timings input[type=checkbox]").trigger("change");
</script>