<?php $form = $this->addForm; ?>
<style>
#gMap{
 height: 350px;
 width: 940px;
}
</style>
<div class="title">
	<h3><?php echo $this->pageTitle;?></h3>
	<hr />
</div>
<div class="margin-top20 row">
	<div class="shipper-container">
		<?php echo $this->form()->openTag($form);?>
		<?php echo $this->formRow($form->get('department_id')); ?>
		<div class="span5">
			<div class="control-group">
				<label class="control-label" for="name">Department Name</label>
				<div class="controls">
					<?php echo $this->formRow($form->get('name')); ?>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="name">Broker</label>
				<div class="controls" style='width:291px'>
					<?php echo $this->formRow($form->get('broker_id')); ?>
				</div>
			</div>
			<div class="text-center" style="margin-top:15px">
            	<?php echo $this->formSubmit($form->get('submit')); ?>
			</div>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>

<div id="invalid-company-template" class="modal hide fade">
	<div class="modal-body">
		<div class="alert  alert-block">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4>Department Not Saved!</h4>
			<h5>Please check below shown errors:</h5>
			<div id="company-errors"></div>
		</div>
	</div>
</div>
<div id="valid-company-template" class="modal hide fade">
	<div class="modal-body">
		<div class="alert  alert-success">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4>Department saved successfuly</h4>
			<div id="company-messages">
				You will now be redirected to department listings.
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$(document).on("submit","#frm_manage",function(e){
		if(!e.isDefaultPrevented()){
			var companyForm = $(this);
			var message = false;
			companyForm.queue(function(next){
				message = new Message({
                    beforeShow:function (self) {
                        this.alternateMessage = this.showLoadingMessage("Please wait while saving department...");
                    },
                    onBlock:next
                });
			}).queue(function(next){
				$.ajax({
					url : companyForm.attr("action"),
					data : companyForm.serialize(),
					type : "POST",
					dataType : "json",
					success : function(data){
						if(data.response && data.response.success && data.redirect_url){
							$("#valid-company-template").modal("show");
							setTimeout(function(){
								document.location.href = data.redirect_url;
							},1000);
						} else {
							$("#company-errors").html(data.response.message);
							$("#invalid-company-template").modal("show");
						}
					},
					error : function(){
						next();
					} 
				}).complete(next);
			}).queue(function(next){
				message.close();
				next();
			});
			e.preventDefault();
		}
	});
});

</script>