<link rel="stylesheet"
	href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script
	src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<style>

#storeroom, #atticroom, #carshade, #washroom {
    height: 100px;
    line-height: 100px;
    margin: 35px;
    width: 128px;
    display:none;
}
#garden, #hall{
	width:415px;
	display:none;
}
#raw,#building,#rawoffice {
	min-height: 300px;
	min-width: 443px;
	background-color: #F5F5F5;
	display: inline-block;
	border: 1px solid #F5E6F5;
	
}
#floor1,#floor2,#floor3{
	min-width:443px;
	min-height:200px;
	background-color: #FFE4B5;
	margin:8px;
	line-height:2;
	font-size:15px;
	text-align:center;
	display:inline-block;
}
#raw {
	margin-left: 40px;
	padding:20px;
	display:none;
}

#building {
	margin-left: 125px;
	padding:20px;
	background-color:#FFE4B5;
	border:1px solid #B2BDFF;
	display:none;
}

.draggable {
	float: left;
	height: 150px;
	width: 200px;
	background-color: #117EC2;
	color: #FFFFFF;
	margin: 8px;
	text-align: center;
	font-size:15px;
}
.editablespan{
	margin:65px 0 0 83px;
}

</style>
<?php $form = $this->addForm;?>
<div class="title">
	<h3>
		<?php echo $this->pageTitle;?>
	</h3>
	<hr />
</div>
<div class="margin-top20 row">
	<div class="shipper-container">
		<?php echo $this->form()->openTag($form);?>
		<?php echo $this->formRow($form->get('builder_id')); ?>
		<div class="span5">
			<div class="control-group">
				<label class="control-label" for="name">Broker Name</label>
				<div class="controls">
					<?php echo $this->formRow($form->get('name')); ?>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="name">Building Type</label>
				<div class="controls" style='width: 291px'>
					<?php echo $this->formRow($form->get('type')); ?>
				</div>
			</div>
			<div class="control-group">
				<div id='raw' class='connectedSortable'>
					<div class='draggable' id='bedroom'>Bed Room</div>
					<div class='draggable' id='hall'>Hall</div>
					<div class='draggable' id='kitchen'>Kitchen</div>
					<div class='draggable' id='washroom'>Wash Room</div>
					<div class='draggable' id='storeroom'>Store Room</div>
					<div class='draggable' id='atticroom'>Attic Room</div>
					<div class='draggable' id='garden'>Garden</div>
					<div class='draggable' id='carshade'>Car Shade</div>
				</div>
				<div id='rawoffice' class='officeconnector'>
					<div class='draggable' id='office'>
						<span class='editablespan'>Office</span>
					</div>
					<div class='draggable' id='shop'>
						<span class='editablespan'>Shop</span>
					</div>
				</div>
			</div>
		</div>
		<div class='span5'>
			<div class="control-group">
				<div id='building' class='droppable connectedSortable'></div>
				<div id='office'>
					<div id='floor1' class='officeconnected'><p>Floor 1</p></div>
					<div id='floor2' class='officeconnected'>Floor 2</div>
					<div id='floor3' class='officeconnected'>Floor 3</div>
				</div>
			</div>
		</div>
		<div class='span12'>
			<div class="control-group">
				<div class="text-center" style="margin-top: 15px">
					<?php echo $this->formSubmit($form->get('submit')); ?>
				</div>
			</div>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>

<div id="invalid-company-template" class="modal hide fade">
	<div class="modal-body">
		<div class="alert  alert-block">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4>Broker Not Saved!</h4>
			<h5>Please check below shown errors:</h5>
			<div id="company-errors"></div>
		</div>
	</div>
</div>
<div id="valid-company-template" class="modal hide fade">
	<div class="modal-body">
		<div class="alert  alert-success">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4>Broker saved successfuly</h4>
			<div id="company-messages">You will now be redirected to builder
				listings.</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	//Checking what kind of building it is
	buildingType = $('select[name=type]').val();
	//sending structure of residence while submiting form
	var structure = "<?php echo isset($this->structure)?$this->structure:"null"; ?>";
	if(structure.length != 0){
		var arraystructure = structure.split(',');
		$.each(arraystructure,function(key,value){
			$('#building').append("<div id='"+value+"' class='draggable' style=''>"+value+"</div>")
		});
	}
	//creating residence builder
	$( "#raw" ).sortable({
        connectWith: ".connectedSortable",
        remove: function(event, ui) {
            ui.item.clone().appendTo('#building');
            $(this).sortable('cancel');
        }
    }).disableSelection();

	/*$( "#building" ).sortable({
        connectWith: ".connectedSortable"
    }).disableSelection();*/

    //For building Office
   	$( "#rawoffice" ).sortable({
        connectWith: ".officeconnected",
    }).disableSelection();

	$( ".officeconnected" ).sortable({
        connectWith: ".officeconnector",
        receive: function(event, ui) {
            ui.item.clone().appendTo('#rawoffice').find('.ui-resizable-handle').remove().end().resizable({
				containment:'.officeconnected'	
            });
        }
    }).disableSelection();
	
	$(document).on('dblclick','.draggable span', function() {
        $(this).attr('contentEditable', true);
        $(this).focus();
    }).blur(function(){
        $(this).attr('contentEditable', false);
        $(this).focusout();
    });

    $('.draggable').resizable({
		containment:'.officeconnected'
    });
    
	$(document).on("submit","#frm_manage",function(e){
		if(!e.isDefaultPrevented()){
			var companyForm = $(this);
			if(buildingType == 'Commercial'){
				str = "";
				$('#floor1 .draggable').each(function(k,el){
					var blocks = [];
					blocks.push($(this).find('span').text().trim());
				    blocks.push($(this).height());
				    blocks.push($(this).width());
				    str += blocks.join(",");
				    str += '$'; 
				});
				str = str.substring(0, str.length - 1);
				console.log(str);
				return false;
			}else{
				floor1 = $('#floor1').sortable("toArray");
				structure = buildingstructure + "";	
			}
			var message = false;
			companyForm.queue(function(next){
				message = new Message({
                    beforeShow:function (self) {
                        this.alternateMessage = this.showLoadingMessage("Please wait while saving builder...");
                    },
                    onBlock:next
                });
			}).queue(function(next){
				$.ajax({
					url : companyForm.attr("action"),
					data : companyForm.serialize()+'&configuration='+structure,
					type : "POST",
					dataType : "json",
					success : function(data){
						if(data.response && data.response.success && data.redirect_url){
							$("#valid-company-template").modal("show");
							setTimeout(function(){
								document.location.href = data.redirect_url;
							},1000);
						} else {
							$("#company-errors").html(data.response.message);
							$("#invalid-company-template").modal("show");
						}
					},
					error : function(){
						next();
					} 
				}).complete(next);
			}).queue(function(next){
				message.close();
				next();
			});
			e.preventDefault();
		}
	});
});
</script>
