<link rel="stylesheet"
	href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script
	src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<style>

#storeroom, #atticroom, #carshade, #washroom {
    height: 100px;
    line-height: 100px;
    margin: 35px;
    width: 128px;
}
#garden, #hall{
	width:415px;
}
#raw,#building {
	min-height: 300px;
	min-width: 443px;
	background-color: #F5F5F5;
	display: inline-block;
}

#raw {
	margin-left: 40px;
	padding:20px;
}

#building {
	margin-left: 125px;
	padding:20px;
	background-color:#FFE4B5;
}

.draggable {
	float: left;
	height: 150px;
	width: 200px;
	background-color: #117EC2;
	color: #FFFFFF;
	margin: 8px;
	text-align: center;
	line-height:150px;
	font-size:15px;
}
</style>
<?php $form = $this->addForm;?>
<div class="title">
	<h3>
		<?php echo $this->pageTitle;?>
	</h3>
	<hr />
</div>
<div class="margin-top20 row">
	<div class="shipper-container">
		<?php echo $this->form()->openTag($form);?>
		<?php echo $this->formRow($form->get('builder_id')); ?>
		<div class="span5">
			<div class="control-group">
				<label class="control-label" for="name">Broker Name</label>
				<div class="controls">
					<?php echo $this->formRow($form->get('name')); ?>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="name">Building Type</label>
				<div class="controls" style='width: 291px'>
					<?php echo $this->formRow($form->get('type')); ?>
				</div>
			</div>
			<div class="control-group">
				<div id='raw' class='connectedSortable'>
					<div class='draggable' id='bedroom'>Bed Room</div>
					<div class='draggable' id='hall'>Hall</div>
					<div class='draggable' id='kitchen'>Kitchen</div>
					<div class='draggable' id='washroom'>Wash Room</div>
					<div class='draggable' id='storeroom'>Store Room</div>
					<div class='draggable' id='atticroom'>Attic Room</div>
					<div class='draggable' id='garden'>Garden</div>
					<div class='draggable' id='carshade'>Car Shade</div>
				</div>
			</div>
		</div>
		<div class='span5'>
			<div class="control-group">
				<div id='building' class='droppable connectedSortable'></div>
			</div>
		</div>
		<div class='span12'>
			<div class="control-group">
				<div class="text-center" style="margin-top: 15px">
					<?php echo $this->formSubmit($form->get('submit')); ?>
				</div>
			</div>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>

<div id="invalid-company-template" class="modal hide fade">
	<div class="modal-body">
		<div class="alert  alert-block">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4>Broker Not Saved!</h4>
			<h5>Please check below shown errors:</h5>
			<div id="company-errors"></div>
		</div>
	</div>
</div>
<div id="valid-company-template" class="modal hide fade">
	<div class="modal-body">
		<div class="alert  alert-success">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4>Broker saved successfuly</h4>
			<div id="company-messages">You will now be redirected to builder
				listings.</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	var structure = "<?php echo isset($this->structure)?$this->structure:"null"; ?>";
	if(structure.length != 0){
		var arraystructure = structure.split(',');
		$.each(arraystructure,function(key,value){
			$('#building').append("<div id='"+value+"' class='draggable' style=''>"+value+"</div>")
		});
	}
	$( "#raw" ).sortable({
        connectWith: ".connectedSortable",
        remove: function(event, ui) {
            ui.item.clone().appendTo('#building');
            $(this).sortable('cancel');
        }
    }).disableSelection();

	$( "#building" ).sortable({
        connectWith: ".connectedSortable"
    }).disableSelection();
	$(document).on("submit","#frm_manage",function(e){
		if(!e.isDefaultPrevented()){
			var companyForm = $(this);
			var buildingstructure = $('#building').sortable("toArray");
			structure = buildingstructure + "";
			var message = false;
			companyForm.queue(function(next){
				message = new Message({
                    beforeShow:function (self) {
                        this.alternateMessage = this.showLoadingMessage("Please wait while saving builder...");
                    },
                    onBlock:next
                });
			}).queue(function(next){
				$.ajax({
					url : companyForm.attr("action"),
					data : companyForm.serialize()+'&configuration='+structure,
					type : "POST",
					dataType : "json",
					success : function(data){
						if(data.response && data.response.success && data.redirect_url){
							$("#valid-company-template").modal("show");
							setTimeout(function(){
								document.location.href = data.redirect_url;
							},1000);
						} else {
							$("#company-errors").html(data.response.message);
							$("#invalid-company-template").modal("show");
						}
					},
					error : function(){
						next();
					} 
				}).complete(next);
			}).queue(function(next){
				message.close();
				next();
			});
			e.preventDefault();
		}
	});
});
</script>
